permalink: /:categories/:title/
collections:
  units:
    output: false
  lessons:
    output: true
    permalink: /:collection/:title/
  homework:
    output: true
    permalink: /:collection/:title/
  projects:
    output: true
    permalink: /:collection/:title/
  meetings:
    output: true
    permalink: /:collection/:title/
  topics:
    output: true
    permalink: /:collection/:title/
defaults:
  -
    scope:
      path: ""
      type: "lessons"
    values:
      layout: "lesson"
  -
    scope:
      path: ""
      type: "homework"
    values:
      layout: "homework"
  -
    scope:
      path: ""
      type: "projects"
    values:
      layout: "project"
  -
    scope:
      path: ""
      type: "meetings"
    values:
      layout: "meeting"
  -
    scope:
      path: ""
      type: "topics"
    values:
      layout: "topic"

  -
    scope:
      path: "lessons/design-thinking"
    values:
      unit: 1
  -
    scope:
      path: "lessons/interaction-design"
    values:
      unit: 2
  -
    scope:
      path: "lessons/information-architecture"
    values:
      unit: 3
  -
    scope:
      path: "lessons/web-development"
    values:
      unit: 4
  -
    scope:
      path: "lessons/review"
    values:
      unit: 5
  -
    scope:
      path: "lessons/careers"
    values:
      unit: 6

  -
    scope:
      path: "projects/design-thinking"
    values:
      unit: 1
  -
    scope:
      path: "projects/interaction-design"
    values:
      unit: 2
  -
    scope:
      path: "projects/information-architecture"
    values:
      unit: 3
  -
    scope:
      path: "projects/web-development"
    values:
      unit: 4
  -
    scope:
      path: "projects/review"
    values:
      unit: 5
  -
    scope:
      path: "projects/careers"
    values:
      unit: 6

  -
    scope:
      path: "homework/design-thinking"
    values:
      unit: 1
  -
    scope:
      path: "homework/interaction-design"
    values:
      unit: 2
  -
    scope:
      path: "homework/information-architecture"
    values:
      unit: 3
  -
    scope:
      path: "homework/web-development"
    values:
      unit: 4
  -
    scope:
      path: "homework/review"
    values:
      unit: 5
  -
    scope:
      path: "homework/careers"
    values:
      unit: 6

relative_permalinks: false
future: false
include: ["_redirects"]

host: 0.0.0.0
